Lindsey/requirements for0um fields subset
ACCESS-NRI/umfile_utils pull request #15
Opened 2024-12-04 09:26 UTC by leoberhelman

Following the requirements raised in Issue #14

2025-01-23 19:57 UTC, atteggiani requested changes
Thank you @leoberhelman for this PR.
Overall the field subset function has a good structure and most of the logic works fine.

Please refer to the specific comments for details.

As one with `perturbIC`, I only reviewed the "main" script without reviewing the unit-testing yet. 

After all the comments are addressed I will review the unit-testing too.

2025-01-23 20:04 UTC, atteggiani requested changes

2025-01-23 20:04 UTC, atteggiani commented on src/um_fields_subset.py
> +
Also, in the requirements (#14) is specified to raise a warning if STASH CODES included in the `--include` or `--exclude` options are not present in the input file. 

This logic is not present anywhere within this script. 
Consider adding a function that perform this logic.

2025-01-31 00:00 UTC, leoberhelman commented on src/um_fields_subset.py
> +    return f"{output_filename}{num}"
Yup

2025-02-03 01:20 UTC, leoberhelman commented
I have finished the review edits and I am working changing the units tests.

2025-02-03 01:21 UTC, leoberhelman commented
I added a function to provide a warning when the STASH codes are not in the file

2025-02-03 04:10 UTC, atteggiani requested changes
A few additional minor comments.

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +def field_not_present_warning(fields, stash_list):
```suggestion
def stash_not_present_warning(fields, stash_list):
```

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +    Checks that the fields in the either list provided are present in the file and provides a warning if not.
```suggestion
    Raise a warning for any stash codes included in the input stash_list that are not present within the input fields.
```

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +    stash_list :  list of int
```suggestion
    stash_list :  set of int
```

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +        Either the exclude or include STASH item code list.
```suggestion
```

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +        None - gives a warning.
```suggestion
        None
```

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +    missing_codes = [code for code in stash_list if code not in existing_codes]
```suggestion
    missing_codes = stash_list - existing_codes
```

You can use subtraction between python sets here to find those present in `stash_list` and not in `existing_codes`.

2025-02-03 04:10 UTC, atteggiani commented on src/um_fields_subset.py
> +        warnings.warn(f"Warning: STASH code(s): {missing_codes} is(are) not present in the input file.")
```suggestion
        warnings.warn(f"The following STASH codes are not found in the input file: {missing_codes}")
```

2025-02-12 01:33 UTC, atteggiani requested changes
Thank you @leoberhelman, it all looks good!

My comments are very minor.

2025-02-12 01:33 UTC, atteggiani commented on src/um_fields_subset.py
> +    A string of user input for the --exlude or --include values
```suggestion
    value: str
    A string of comma-separated positive integers
```

2025-02-12 01:33 UTC, atteggiani commented on src/um_fields_subset.py
> +        values : A list of the int STASH codes that are either to be excluded or included
```suggestion
        list
        A list of STASH codes to be excluded or included
```

2025-02-12 01:33 UTC, atteggiani commented on src/um_fields_subset.py
> +            raise ValueError
```suggestion
            raise ValueError(msg)
```
It's always good to add an error message.

2025-02-12 01:33 UTC, atteggiani commented on src/um_fields_subset.py
> +        raise argparse.ArgumentTypeError("All values must be positive integers.")
```suggestion
        raise argparse.ArgumentTypeError(msg)
```

2025-02-12 01:33 UTC, atteggiani commented on src/um_fields_subset.py
> +    """
```suggestion
    """
    msg = "All values must be positive integers."
```

2025-02-20 22:36 UTC, atteggiani approved these changes
Thank you @leoberhelman for your work on this!
Looks good! 

In my latest commits, I rebased the branch to `main` and fixed the path issues (`um_fields_subset.py` now is within the `src/umfile_utils` directory).

I also added a couple of tests that were missing, to bring coverage to 100%.

2025-02-20 23:41 UTC, MartinDix commented
Apologies for having new ideas this late in the process.

In `um2nc` the input and output files are positional arguments. In my original `um_fields_subset` they were both arguments with `-i` and `-o`.  This was unnecessarily confusing (even to me and I wrote it).

 `um_fields_subset`  now has an optional output argument but would it be clearer to have a compulsory positional output argument to be consistent with `um2nc`?

`um2nc` has space separated lists for the include and exclude options while `um_fields_subse`t has comma separated lists. I used the space separated lists for `um2n`c because it was simpler with `argparse`. I didn't realise it was possible to use a conversion function like `type=convert_to_list`. I think it'd be better to choose one style or the other.

The use of `um2nc` in payu suites doesn't use include/exclude so I think we're free to choose whichever is better or considered more standard.

2025-02-21 03:21 UTC, atteggiani commented
Hi @MartinDix, 
I think you raise valid points and it's always good to keep consistency among different tools.

> In `um2nc` the input and output files are positional arguments. In my original `um_fields_subset` they were both arguments with `-i` and `-o`. This was unnecessarily confusing (even to me and I wrote it).
> 
> `um_fields_subset` now has an optional output argument but would it be clearer to have a compulsory positional output argument to be consistent with `um2nc`?

I think this behaviour should be changed in `um2nc` to be consistent with `um_fields_subset` (and all the other tools in `umfile_utils`) instead (i.e.: having a compulsory positional input argument and an optional output argument, with a default naming of the output if the output argument is not produced). 
I think it is always good to have a default output produced, so the user doesn't necessarily need to specify an output if they are fine with the default one (for `um2nc` it would make even more sense, because the default output could simply be `.nc` appended to the input name). 

> `um2nc` has space separated lists for the include and exclude options while `um_fields_subset` has comma separated lists. I used the space separated lists for `um2n`c because it was simpler with `argparse`. I didn't realise it was possible to use a conversion function like `type=convert_to_list`. I think it'd be better to choose one style or the other.
> 
> The use of `um2nc` in payu suites doesn't use include/exclude so I think we're free to choose whichever is better or considered more standard.

I can't identify any valid reason to prefer an option over the other here.
The only (very minor) reason that would make me prefer a comma-separated list, is that it could be copied directly from the printed output of a python list. 
But I don't have strong feelings about which one we should go with. 
Actually, we could also allow both (`include`/`exclude` can be a comma-separated or a space-separated list), without too much of a change in the logic (we would only need to slight change the `convert_to_list` function and the description of the `include`/`exclude` arguments. I think allowing both would probably make sense.

What do you think?

2025-02-25 00:34 UTC, atteggiani commented
After talking with Martin, we concluded that:
- required input(s) should be provided using positional arguments
- output paths should be provided using `-o/--option` optional argument and have a default (if the option is not provided)
- `--exclude/include` optional arguments should be structured as a comma-separated list of values (one single value, so if there is any space between the commas and the values, the whole list should be enclosed within quotes)

Based on the above, this PR can be safely merged as the points above are already included.

2025-02-25 02:57 UTC, MartinDix approved these changes
Looks good

2025-02-25 03:55 UTC, merged